export const MovieCategory = [
  { category: '한국 영화', movies: [] },
  { category: '외국 영화', movies: [] },
  { category: '어린이', movies: [] },
  { category: '가족', movies: [] },
  { category: '오리지널', movies: [] },
  { category: '액션', movies: [] },
  { category: '스릴러', movies: [] },
  { category: 'SF', movies: [] },
  { category: '판타지', movies: [] },
  { category: '범죄', movies: [] },
  { category: '호러', movies: [] },
  { category: '다큐멘터리', movies: [] },
  { category: '로맨스', movies: [] },
  { category: '코미디', movies: [] },
  { category: '애니', movies: [] },
];
